services:
  - type: web
    name: discord-absen-bot
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: FIREBASE_API_KEY
        sync: false
      - key: FIREBASE_AUTH_DOMAIN
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_STORAGE_BUCKET
        sync: false
      - key: FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: FIREBASE_APP_ID
        sync: false
